export interface ExoticI {
    id: number;
    name: string;
    type: string;
    terpene: string;
    thc: number;
    cbd: number;
}

export const Exotics: ExoticI[] = [
    {
        id: 0,
        name: 'Dank Exotic Nugget',
        type: 'Hybrid',
        terpene: 'golden',
        thc: 100,
        cbd: 100,
    },
    {
        id: 1,
        name: 'Tropicana Cookies',
        type: 'Sativa',
        terpene: 'Caryophyllene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 2,
        name: 'Granddaddy Purple',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 3,
        name: 'Purple Punch',
        type: 'Indica',
        terpene: 'Caryophyllene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 4,
        name: 'Afghan Goo',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 5,
        name: 'Bubba Kush',
        type: 'Indica',
        terpene: 'Caryophyllene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 6,
        name: 'Purple Kush',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 7,
        name: 'G 13',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 8,
        name: 'Blackberry Kush',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 9,
        name: 'LA Confidential',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 10,
        name: 'Hindu Kush',
        type: 'Indica',
        terpene: 'Limonene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 11,
        name: '9lb Hammer',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 12,
        name: 'Romulan',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 13,
        name: 'Purple Urkle',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 14,
        name: 'Pink OG',
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 15,
        name: 'OG Kush',
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 16,
        name: 'Dosi',
        type: 'Indica',
        terpene: 'Limonene',
        thc: 20,
        cbd: 1,
    },
    {
        id: 17,
        name: 'Afghani',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 18,
        name: 'Ice Cream Cake',
        type: 'Indica',
        terpene: 'Limonene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 19,
        name: 'Slurricane',
        type: 'Indica',
        terpene: 'Limonene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 20,
        name: 'Apple Fritter',
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 25,
        cbd: 1,
    },
    {
        id: 21,
        name: 'Gorilla Cookies',
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 22,
        name: 'OG Kush Breath',
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 24,
        cbd: 1,
    },
    {
        id: 23,
        name: 'Peanut Butter Breath',
        type: 'Hybrid',
        terpene: 'Caryophyllene',
        thc: 20,
        cbd: 1,
    },
    {
        id: 24,
        name: 'LA Kush Cake',
        type: 'Hybrid',
        terpene: 'Caryophyllene',
        thc: 23,
        cbd: 1,
    },
    {
        id: 25,
        name: 'Master Kush',
        type: 'Indica',
        terpene: 'Caryophyllene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 26,
        name: 'Skywalker Kush',
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 2,
    },
    {
        id: 27,
        name: 'Grape Ape',
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 28,
        name: 'Banana Punch',
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 20,
        cbd: 1,
    },
    {
        id: 29,
        name: 'Sour Diesel',
        type: 'Sativa',
        terpene: 'Caryophyllene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 30,
        name: 'Durban Poison',
        type: 'Sativa',
        terpene: 'Humulene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 31,
        name: 'Pineapple Express',
        type: 'Sativa',
        terpene: 'Caryophyllene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 32,
        name: 'Maui Wowie',
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 33,
        name: 'Acapulco Gold',
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 34,
        name: 'Green Crack',
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 35,
        name: 'Super Silver Haze',
        type: 'Sativa',
        terpene: 'Humulene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 36,
        name: 'White Fire OG',
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 37,
        name: `Lamb's Bread`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 38,
        name: `Island Sweet Skunk`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 39,
        name: `Super Lemon Haze`,
        type: 'Sativa',
        terpene: 'Linalool',
        thc: 18,
        cbd: 1,
    },
    {
        id: 40,
        name: `Gelato`,
        type: 'Hybrid',
        terpene: 'Caryophyllene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 41,
        name: `Blue Dream`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 42,
        name: `Jack Herer`,
        type: 'Sativa',
        terpene: 'Pinene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 43,
        name: `Jilly Bean`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 44,
        name: `Tangie`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 45,
        name: `Headband`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 46,
        name: `Haze OG`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 47,
        name: `Skunk One`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 48,
        name: `Chocolope`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 49,
        name: `Vanilla Frosting`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 50,
        name: `Strawberry Banana`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 51,
        name: `Zkittlez`,
        type: 'Indica',
        terpene: 'Caryophyllene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 52,
        name: `Bruce Banner`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 53,
        name: `SFV OG`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 20,
        cbd: 1,
    },
    {
        id: 54,
        name: `Zookies`,
        type: 'Hybrid',
        terpene: 'Caryophyllene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 55,
        name: `Bubble Gum`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 56,
        name: `Papaya`,
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 15,
        cbd: 1,
    },
    {
        id: 57,
        name: `Guava`,
        type: 'Sativa',
        terpene: 'Caryophyllene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 58,
        name: `Lemonade`,
        type: 'Hybrid',
        terpene: 'Humulene',
        thc: 20,
        cbd: 1,
    },
    {
        id: 59,
        name: `Harlequin`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 5,
        cbd: 9,
    },
    {
        id: 60,
        name: `Black Jack`,
        type: 'Hybrid',
        terpene: 'Humulene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 61,
        name: `Apple Jack`,
        type: 'Hybrid',
        terpene: 'Humulene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 62,
        name: `Red Congolese`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 23,
        cbd: 1,
    },
    {
        id: 63,
        name: `Runtz`,
        type: 'Sativa',
        terpene: 'Caryophyllene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 64,
        name: `White Widow`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 65,
        name: `Cherry Pie`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 66,
        name: `AK 47`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 67,
        name: `Fruity Pebbles`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 68,
        name: `Candyland`,
        type: 'Sativa',
        terpene: 'Caryophyllene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 69,
        name: `XJ 13`,
        type: 'Hybrid',
        terpene: 'Humulene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 70,
        name: `ACDC`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 14,
        cbd: 1,
    },
    {
        id: 71,
        name: `Lava Cake`,
        type: 'Hybrid',
        terpene: 'Caryophyllene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 72,
        name: `Banana Kush`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 73,
        name: `Triangle Kush`,
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 20,
        cbd: 1,
    },
    {
        id: 74,
        name: `Dutch Treat`,
        type: 'Hybrid',
        terpene: 'Humulene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 75,
        name: `MAC`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 22,
        cbd: 1,
    },
    {
        id: 76,
        name: `Mimosa`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 77,
        name: `Northern Lights`,
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 16,
        cbd: 1,
    },
    {
        id: 78,
        name: `GMO Cookies`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 26,
        cbd: 1,
    },
    {
        id: 79,
        name: `Alien OG`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 80,
        name: `Superglue`,
        type: 'Hybrid',
        terpene: 'Caryophyllene',
        thc: 20,
        cbd: 1,
    },
    {
        id: 81,
        name: `North Star`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 82,
        name: `Llama Kush`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 83,
        name: `Gorilla Punch`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 84,
        name: `Glacier Glue`,
        type: 'Hybrid',
        terpene: 'Humulene',
        thc: 4,
        cbd: 6,
    },
    {
        id: 85,
        name: `OG Tonic`,
        type: 'Hybrid',
        terpene: 'Pinene',
        thc: 2,
        cbd: 13,
    },
    {
        id: 86,
        name: `Purple Lamborghini`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 87,
        name: `Lime Tart`,
        type: 'Indica',
        terpene: 'Pinene',
        thc: 18,
        cbd: 3,
    },
    {
        id: 88,
        name: `Blackberry OG`,
        type: 'Hybrid',
        terpene: 'Pinene',
        thc: 15,
        cbd: 3,
    },
    {
        id: 89,
        name: `Blue Tahoe`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 20,
        cbd: 3,
    },
    {
        id: 90,
        name: `Golden Gage`,
        type: 'Hybrid',
        terpene: 'Humulene',
        thc: 21,
        cbd: 1,
    },
    {
        id: 91,
        name: `Black Roses`,
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 25,
        cbd: 1,
    },
    {
        id: 92,
        name: `Nuclear Cookies`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 22,
        cbd: 2,
    },
    {
        id: 93,
        name: `Purple Aurora`,
        type: 'Hybrid',
        terpene: 'Linalool',
        thc: 18,
        cbd: 1,
    },
    {
        id: 94,
        name: `Galactic Jack`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 95,
        name: `Full Moon`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 13,
        cbd: 1,
    },
    {
        id: 96,
        name: `White Lotus`,
        type: 'Hybrid',
        terpene: 'Caryophyllene',
        thc: 19,
        cbd: 1,
    },
    {
        id: 97,
        name: `Modified Bananas`,
        type: 'Hybrid',
        terpene: 'Myrcene',
        thc: 31,
        cbd: 1,
    },
    {
        id: 98,
        name: `Silverback Gorilla`,
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 18,
        cbd: 1,
    },
    {
        id: 99,
        name: `Purple Martian`,
        type: 'Indica',
        terpene: 'Myrcene',
        thc: 17,
        cbd: 1,
    },
    {
        id: 100,
        name: `Jungle Juice`,
        type: 'Hybrid',
        terpene: 'Limonene',
        thc: 11,
        cbd: 1,
    },
    {
        id: 101,
        name: `Alpha Blue`,
        type: 'Sativa',
        terpene: 'Myrcene',
        thc: 19,
        cbd: 1,
    },
]